In [2]:
import pandas as pd

In [81]:
df = pd.read_csv("Sample Data.csv")

In [36]:
df.head(20)

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date
0,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.2,01/07/1998 00:00,31/05/2023 00:00
1,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.8,01/07/1998 00:00,31/05/2023 00:00
2,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.4,01/08/2005 00:00,31/05/2023 00:00
3,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.6,01/08/2005 00:00,31/05/2023 00:00
4,1140481 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.2,01/07/2013 00:00,31/05/2023 00:00
5,1140481 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.8,01/07/2013 00:00,31/05/2023 00:00
6,1100643 2,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 2,F,0.3,27/03/2000 00:00,31/05/2023 00:00
7,1100643 2,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 2,F,0.7,27/03/2000 00:00,31/05/2023 00:00
8,1100891 2,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 2,M,0.3,01/07/2013 00:00,31/05/2023 00:00
9,1100891 2,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 2,M,0.7,01/07/2013 00:00,31/05/2023 00:00
10,1102618 4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 4,F,0.3,26/03/1989 00:00,31/05/2023 00:00
11,1102618 4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 4,F,0.7,26/03/1989 00:00,31/05/2023 00:00
12,1050572 6,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Fixed,Fixed-term,Acad-Rel Administrative,Grade 6,F,1.0,09/05/2022 00:00,31/05/2023 00:00
13,1090424 7,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Permanent,Perm - acting up,Acad-Rel Administrative,Grade 7,F,1.0,20/08/2007 00:00,31/05/2023 00:00
14,1100527 6,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Permanent,Perm on temp appt,Acad-Rel Administrative,Grade 6,F,1.0,08/01/2018 00:00,31/05/2023 00:00
15,1100547 7,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Permanent,Perm on temp appt,Acad-Rel Administrative,Grade 7,F,1.0,22/07/2019 00:00,31/05/2023 00:00
16,1100576 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.3,16/01/2023 00:00,31/05/2023 00:00
17,1100576 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.7,16/01/2023 00:00,31/05/2023 00:00
18,1090871or,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Pro-Vice-Chancellor,F,1.0,01/01/2003 00:00,31/05/2023 00:00
19,1090129 B,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Director B,F,1.0,26/08/1996 00:00,31/05/2023 00:00

In [ ]:
# How many rows?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Staff Key            30000 non-null  object
 1   faculty              30000 non-null  object
 2   school               30000 non-null  object
 3   broad_category       30000 non-null  object
 4   broad_contract_type  30000 non-null  object
 5   contract_type        30000 non-null  object
 6   contract_category    30000 non-null  object
 7   grade                30000 non-null  object
 8   gender               30000 non-null  object
 9   calc_fte             30000 non-null  float64
 10  start_date           30000 non-null  object
 11  reporting_date       30000 non-null  object
dtypes: float64(1), object(11)
memory usage: 2.7+ MB

30000 rows. All data are non-null

In [42]:
# Dictionary of unique column values
unique_dict = {col: df[col].unique() for col in df.columns}
unique_dict

{'Staff Key': array(['1140547C4', '1140403 1', '1140481 1', ..., '1110482 7',
        '1100568 7', '1130583 6'], shape=(1336,), dtype=object),
 'faculty': array(['Arts, Humanities and Social Sciences', 'Belfast Region City Deal',
        'Corporate', 'Engineering and Physical Sciences'], dtype=object),
 'school': array(['Faculty Office AHSS',
        'Inst for Global Peace, Security and Justice',
        'Inst of Professional Legal Studies', "Queen's Business School",
        'School of Arts, English and Languages',
        'School of History, Anthropology, Philosophy and Politics',
        'School of Law',
        'School of Social Sciences, Education and Social Work', 'AMIC',
        'BRCD Directorate Office', 'iREACH Health', 'Momentum 1.0',
        'University General', 'Faculty Office EPS'], dtype=object),
 'broad_category': array(['Academic', 'Professional and Support', 'Academic Education',
        'Research'], dtype=object),
 'broad_contract_type': array(['Permanent', 'Fixed'], dtype=object),
 'contract_type': array(['Perm on temp appt', 'Fixed-term', 'Perm - acting up', 'Permanent',
        'Fixed-term - SPC', 'Permanent (Flex Retirement)',
        'Fixed-term - acting up'], dtype=object),
 'contract_category': array(['Academic Non-Clinical', 'Acad-Rel Administrative', 'Clerical',
        'Clerical Intern/Student', 'Academic Non-Clinical (Education)',
        'Research', 'Technical', 'Acad-Rel Computer',
        'Teaching Cons/Asst/Assoc', 'Acad-Rel ORS', 'Research Academic',
        'Operational Intern/Student', 'Technical Intern/Student',
        'Catering/Ancillary/Sport', 'Cleaning'], dtype=object),
 'grade': array(['AC4', 'Professorial Range 1', 'Professorial Range 2',
        'Professorial Range 4', 'Grade 6', 'Grade 7',
        'Pro-Vice-Chancellor', 'Director B', 'Grade 4', 'Grade 5',
        'Grade 9', 'Grade 1', 'Grade 2', 'Grade 8', 'Directors', 'AC5',
        'Grade 10', 'Grade 3', 'AC3', 'AC2', 'AC1', 'Grade 10B',
        'Professorial Range 3', 'Grade 10A', 'AFC 8A', 'ECIT Grade 1',
        'ECIT Grade 2', 'ECIT Grade 3', 'ECIT Grade 4'], dtype=object),
 'gender': array(['F', 'M'], dtype=object),
 'calc_fte': array([0.2   , 0.8   , 0.4   , 0.6   , 0.3   , 0.7   , 1.    , 0.9   ,
        0.5   , 0.48  , 0.1   , 0.23  , 0.27  , 0.25  , 0.32  , 0.134 ,
        0.268 , 0.55  , 0.75  , 0.69  , 0.05  , 0.45  , 0.65  , 0.16  ,
        0.64  , 0.14  , 0.95  , 0.33  , 0.67  , 0.42  , 0.58  , 0.44  ,
        0.56  , 0.86  , 0.85  , 0.13  , 0.87  , 0.61  , 0.97  , 0.81  ,
        0.43  , 0.41  , 0.105 , 0.595 , 0.104 , 0.328 , 0.24  , 0.36  ,
        0.15  , 0.68  , 0.252 , 0.348 , 0.73  , 0.075 , 0.014 , 0.056 ,
        0.07  , 0.225 , 0.275 , 0.2002, 0.4998, 0.11  , 0.96  , 0.94  ,
        0.71  ]),
 'start_date': array(['01/07/1998 00:00', '01/08/2005 00:00', '01/07/2013 00:00',
        '27/03/2000 00:00', '26/03/1989 00:00', '09/05/2022 00:00',
        '20/08/2007 00:00', '08/01/2018 00:00', '22/07/2019 00:00',
        '16/01/2023 00:00', '01/01/2003 00:00', '26/08/1996 00:00',
        '25/11/1996 00:00', '09/12/2002 00:00', '18/01/2010 00:00',
        '30/10/2017 00:00', '05/11/2018 00:00', '09/06/1997 00:00',
        '16/03/2021 00:00', '17/10/2022 00:00', '01/02/1996 00:00',
        '01/11/2008 00:00', '13/09/2016 00:00', '24/04/2017 00:00',
        '10/09/2018 00:00', '03/10/2018 00:00', '10/06/2019 00:00',
        '26/08/2019 00:00', '01/03/2020 00:00', '07/02/2022 00:00',
        '07/11/2022 00:00', '01/03/2006 00:00', '31/05/2023 00:00',
        '26/11/2018 00:00', '21/05/2018 00:00', '01/06/2023 00:00',
        '01/08/2023 00:00', '16/10/2023 00:00', '27/03/2017 00:00',
        '28/02/2022 00:00', '25/07/2022 00:00', '17/06/2024 00:00',
        '16/07/2024 00:00', '09/07/2024 00:00', '12/08/2024 00:00',
        '09/09/1991 00:00', '27/08/2018 00:00', '01/09/2012 00:00',
        '18/08/2025 00:00', '05/06/2017 00:00', '01/09/2023 00:00',
        '01/09/2008 00:00', '01/09/2016 00:00', '10/02/1992 00:00',
        '01/02/2007 00:00', '15/10/2018 00:00', '01/10/2016 00:00',
        '01/09/2018 00:00', '01/07/1995 00:00', '01/01/2024 00:00',
        '01/09/2022 00:00', '21/01/2008 00:00', '01/01/2021 00:00',
        '01/11/1994 00:00', '01/09/1995 00:00', '01/09/2015 00:00',
        '06/03/2023 00:00', '26/06/2017 00:00', '19/11/2007 00:00',
        '06/08/2001 00:00', '13/11/2023 00:00', '26/02/2024 00:00',
        '08/11/2016 00:00', '19/08/2024 00:00', '01/08/2022 00:00',
        '01/03/2021 00:00', '01/11/2022 00:00', '13/12/2022 00:00',
        '20/07/2015 00:00', '01/10/2019 00:00', '05/09/2022 00:00',
        '16/10/2019 00:00', '01/07/2021 00:00', '17/01/2023 00:00',
        '19/03/2019 00:00', '14/11/2022 00:00', '01/09/2024 00:00',
        '22/07/2024 00:00', '17/08/2022 00:00', '01/12/2006 00:00',
        '01/09/2017 00:00', '01/09/2020 00:00', '21/09/2020 00:00',
        '25/01/2021 00:00', '01/08/2021 00:00', '01/09/2021 00:00',
        '01/11/2021 00:00', '01/12/2021 00:00', '01/07/2022 00:00',
        '01/04/2022 00:00', '01/06/2022 00:00', '19/09/2022 00:00',
        '30/01/2023 00:00', '01/04/2023 00:00', '01/03/1993 00:00',
        '24/09/2018 00:00', '01/09/2005 00:00', '01/09/2006 00:00',
        '01/08/2012 00:00', '12/01/2015 00:00', '21/11/2016 00:00',
        '15/02/2018 00:00', '14/05/2018 00:00', '01/10/2018 00:00',
        '01/01/2019 00:00', '07/01/2019 00:00', '01/04/2019 00:00',
        '23/09/2019 00:00', '16/12/2019 00:00', '01/12/2019 00:00',
        '15/07/2021 00:00', '09/07/2021 00:00', '01/10/2021 00:00',
        '13/06/2022 00:00', '27/09/2022 00:00', '01/10/2022 00:00',
        '01/12/2022 00:00', '01/05/2023 00:00', '01/08/2009 00:00',
        '01/08/2010 00:00', '01/09/2010 00:00', '01/09/2011 00:00',
        '01/10/2012 00:00', '10/10/2012 00:00', '10/12/2012 00:00',
        '29/04/2013 00:00', '01/06/2013 00:00', '23/07/2013 00:00',
        '01/09/2013 00:00', '31/03/2014 00:00', '01/07/2014 00:00',
        '30/03/2015 00:00', '31/03/2015 00:00', '30/06/2015 00:00',
        '01/08/2015 00:00', '01/03/2018 00:00', '01/07/2018 00:00',
        '03/12/2018 00:00', '01/07/2019 00:00', '01/09/2019 00:00',
        '19/12/2022 00:00', '27/02/2023 00:00', '01/12/2014 00:00',
        '10/04/2006 00:00', '28/04/2014 00:00', '24/08/2015 00:00',
        '22/09/2006 00:00', '12/03/2007 00:00', '01/04/2012 00:00',
        '08/10/2012 00:00', '08/04/2013 00:00', '20/09/2017 00:00',
        '20/08/2018 00:00', '04/04/2022 00:00', '31/10/2022 00:00',
        '16/11/2022 00:00', '07/08/1978 00:00', '09/06/2008 00:00',
        '10/09/2012 00:00', '06/01/2020 00:00', '15/11/2021 00:00',
        '14/08/1989 00:00', '08/10/2001 00:00', '20/09/2004 00:00',
        '01/04/2007 00:00', '10/05/2007 00:00', '01/12/2007 00:00',
        '27/11/2017 00:00', '14/02/2018 00:00', '31/08/2020 00:00',
        '17/04/2023 00:00', '01/10/2008 00:00', '01/07/2009 00:00',
        '01/01/2013 00:00', '17/09/2018 00:00', '28/02/2019 00:00',
        '07/10/2022 00:00', '01/01/2000 00:00', '01/06/2003 00:00',
        '01/08/2008 00:00', '01/09/1982 00:00', '30/06/2022 00:00',
        '02/12/2013 00:00', '01/01/1993 00:00', '07/09/2022 00:00',
        '07/07/1997 00:00', '18/05/2020 00:00', '01/06/2009 00:00',
        '26/02/2018 00:00', '16/09/2019 00:00', '22/08/2022 00:00',
        '08/10/2018 00:00', '01/04/2020 00:00', '20/06/2023 00:00',
        '17/06/2019 00:00', '12/06/2023 00:00', '19/06/2023 00:00',
        '05/12/2022 00:00', '19/07/2023 00:00', '01/07/2023 00:00',
        '25/07/2023 00:00', '26/07/2023 00:00', '15/08/2023 00:00',
        '22/08/2023 00:00', '11/09/2023 00:00', '30/07/2018 00:00',
        '01/10/2023 00:00', '30/10/2023 00:00', '01/12/2023 00:00',
        '04/01/2024 00:00', '01/07/2007 00:00', '29/02/2024 00:00',
        '15/04/2024 00:00', '08/04/2024 00:00', '24/06/2024 00:00',
        '01/06/2024 00:00', '08/07/2024 00:00', '23/09/2024 00:00',
        '30/09/2024 00:00', '14/10/2024 00:00', '31/10/2024 00:00',
        '21/10/2024 00:00', '16/10/2024 00:00', '01/11/2024 00:00',
        '01/01/2025 00:00', '12/02/2024 00:00', '08/05/2024 00:00',
        '18/03/2025 00:00', '28/04/2025 00:00', '07/04/2025 00:00',
        '21/05/2025 00:00', '01/05/2025 00:00', '15/03/2010 00:00',
        '16/06/2025 00:00', '25/06/2025 00:00', '01/07/2025 00:00',
        '10/07/2025 00:00', '23/07/2025 00:00', '21/03/2022 00:00',
        '05/12/2023 00:00', '03/09/2021 00:00', '01/10/2001 00:00',
        '19/03/2018 00:00', '01/09/2007 00:00', '01/11/2013 00:00',
        '01/01/2020 00:00', '30/01/2017 00:00', '28/03/2017 00:00',
        '26/03/2018 00:00', '01/08/2018 00:00', '19/11/2018 00:00',
        '08/01/2021 00:00', '31/03/2021 00:00', '10/05/2021 00:00',
        '01/01/2022 00:00', '24/10/1996 00:00', '01/09/2001 00:00',
        '01/08/2002 00:00', '01/09/2002 00:00', '11/08/2003 00:00',
        '01/08/2004 00:00', '01/06/2006 00:00', '01/10/2007 00:00',
        '02/08/2012 00:00', '07/01/2013 00:00', '28/01/2013 00:00',
        '01/02/2013 00:00', '01/05/2013 00:00', '21/08/2013 00:00',
        '01/03/2014 00:00', '01/02/2015 00:00', '09/01/2017 00:00',
        '01/02/2017 00:00', '18/09/2017 00:00', '05/08/2019 00:00',
        '12/11/2019 00:00', '01/02/2020 00:00', '01/09/1991 00:00',
        '01/05/1995 00:00', '01/08/1998 00:00', '04/01/1999 00:00',
        '26/08/1999 00:00', '01/10/2005 00:00', '01/10/2010 00:00',
        '01/04/2015 00:00', '08/11/2006 00:00', '18/08/2003 00:00',
        '10/11/2008 00:00', '09/12/2019 00:00', '26/07/2010 00:00',
        '01/10/1994 00:00', '27/03/1995 00:00', '01/09/1997 00:00',
        '01/02/2001 00:00', '14/07/2003 00:00', '01/12/2005 00:00',
        '02/05/2017 00:00', '01/09/1978 00:00', '01/10/1981 00:00',
        '01/10/1989 00:00', '01/04/1991 00:00', '01/09/1999 00:00',
        '20/09/1999 00:00', '01/08/2007 00:00', '01/01/2011 00:00',
        '01/02/2019 00:00', '01/10/2004 00:00', '01/10/1990 00:00',
        '01/08/2000 00:00', '13/04/2026 00:00', '07/10/2019 00:00',
        '10/05/2018 00:00', '01/04/2021 00:00', '01/03/2023 00:00',
        '19/10/2020 00:00', '09/04/2025 00:00', '01/10/2024 00:00',
        '01/01/2023 00:00', '13/11/2014 00:00', '29/07/2019 00:00',
        '09/01/2023 00:00', '03/05/2020 00:00', '21/09/2015 00:00',
        '29/03/2018 00:00', '01/01/2016 00:00', '19/09/1988 00:00',
        '02/05/2019 00:00', '01/10/2017 00:00', '28/01/2008 00:00',
        '09/08/2021 00:00', '25/04/2022 00:00', '10/10/2022 00:00',
        '13/05/2002 00:00', '01/08/2006 00:00', '20/11/2006 00:00',
        '29/10/2012 00:00', '05/07/2016 00:00', '19/07/2021 00:00',
        '01/09/1986 00:00', '23/10/2000 00:00', '29/01/2001 00:00',
        '31/01/2007 00:00', '29/09/2014 00:00', '02/11/2006 00:00',
        '19/02/2018 00:00', '26/11/2019 00:00', '02/08/1999 00:00',
        '23/06/2003 00:00', '10/03/2008 00:00', '12/09/2016 00:00',
        '27/03/2023 00:00', '15/02/2016 00:00', '17/07/2023 00:00',
        '14/08/2023 00:00', '07/08/2023 00:00', '18/09/2023 00:00',
        '15/09/2023 00:00', '24/07/2014 00:00', '25/09/2023 00:00',
        '18/10/2023 00:00', '06/10/2023 00:00', '04/09/2023 00:00',
        '21/01/2002 00:00', '08/01/2024 00:00', '22/03/2021 00:00',
        '01/03/2024 00:00', '11/03/2024 00:00', '26/04/1999 00:00',
        '01/07/2024 00:00', '27/11/2023 00:00', '26/08/2024 00:00',
        '01/08/2024 00:00', '16/09/2024 00:00', '20/09/2024 00:00',
        '04/11/2024 00:00', '06/01/2025 00:00', '13/01/2025 00:00',
        '10/02/2025 00:00', '08/02/2023 00:00', '02/05/2025 00:00',
        '01/09/2025 00:00', '16/09/2025 00:00', '30/11/2023 00:00',
        '04/11/2019 00:00', '20/10/2025 00:00', '27/10/2025 00:00',
        '12/06/2019 00:00', '10/12/2025 00:00', '03/12/2025 00:00',
        '09/01/2026 00:00', '01/01/2026 00:00', '14/09/2022 00:00',
        '25/01/2022 00:00', '12/09/2022 00:00', '01/08/2003 00:00',
        '01/07/2005 00:00', '03/09/2019 00:00', '01/06/2020 00:00',
        '27/07/2020 00:00', '24/08/2021 00:00', '01/07/1994 00:00',
        '01/09/2003 00:00', '01/09/2004 00:00', '01/01/2007 00:00',
        '16/04/2012 00:00', '01/04/2013 00:00', '19/08/2013 00:00',
        '16/09/2013 00:00', '01/09/2014 00:00', '01/01/2015 00:00',
        '01/11/2016 00:00', '01/01/1991 00:00', '01/08/1999 00:00',
        '01/01/2004 00:00', '01/02/2012 00:00', '01/02/1999 00:00',
        '13/09/1999 00:00', '01/09/2000 00:00', '01/01/2001 00:00',
        '01/09/1992 00:00', '01/05/2017 00:00', '01/08/2019 00:00',
        '12/03/2018 00:00', '01/10/2025 00:00', '11/07/2022 00:00',
        '01/02/2023 00:00', '01/08/2020 00:00', '01/12/2017 00:00',
        '01/07/2020 00:00', '24/01/2022 00:00', '03/08/1981 00:00',
        '01/02/2005 00:00', '20/04/2015 00:00', '28/04/2010 00:00',
        '01/08/2013 00:00', '04/09/2018 00:00', '22/11/2021 00:00',
        '06/02/2023 00:00', '04/05/2004 00:00', '05/06/2018 00:00',
        '01/01/2017 00:00', '08/03/2017 00:00', '16/08/2021 00:00',
        '25/06/2003 00:00', '14/01/2008 00:00', '19/11/2012 00:00',
        '10/01/2017 00:00', '01/06/2017 00:00', '10/09/2019 00:00',
        '29/09/2008 00:00', '22/10/2013 00:00', '09/09/2019 00:00',
        '28/06/1999 00:00', '05/06/2023 00:00', '14/03/2022 00:00',
        '06/11/2023 00:00', '20/12/2023 00:00', '03/04/2017 00:00',
        '18/11/2024 00:00', '09/12/2024 00:00', '06/02/2025 00:00',
        '01/04/2025 00:00', '10/06/2025 00:00', '06/10/2025 00:00',
        '01/02/2026 00:00', '01/02/2021 00:00', '16/03/2023 00:00',
        '21/01/2019 00:00', '28/11/2016 00:00', '14/05/2007 00:00',
        '08/01/2020 00:00', '14/06/2021 00:00', '11/01/2022 00:00',
        '01/11/2019 00:00', '01/07/2016 00:00', '01/08/2016 00:00',
        '23/06/2017 00:00', '01/02/2018 00:00', '23/08/2021 00:00',
        '13/09/2021 00:00', '01/10/2006 00:00', '01/09/2009 00:00',
        '21/08/2012 00:00', '02/01/2014 00:00', '01/08/2017 00:00',
        '01/09/1989 00:00', '14/11/2012 00:00', '31/01/2014 00:00',
        '20/03/2023 00:00', '09/05/2023 00:00', '27/01/2004 00:00',
        '10/09/2007 00:00', '24/08/1987 00:00', '01/11/2003 00:00',
        '18/11/2019 00:00', '01/06/1998 00:00', '01/09/1998 00:00',
        '01/06/2014 00:00', '01/05/2022 00:00', '01/01/1984 00:00',
        '01/01/2005 00:00', '01/12/2018 00:00', '01/09/1977 00:00',
        '01/08/2011 00:00', '09/02/2022 00:00', '27/05/2002 00:00',
        '19/10/2022 00:00', '09/10/2023 00:00', '11/12/2023 00:00',
        '14/08/2024 00:00', '12/09/2024 00:00', '30/09/2025 00:00',
        '01/04/2026 00:00', '01/03/2007 00:00', '24/03/2020 00:00',
        '28/11/2006 00:00', '24/02/2009 00:00', '15/02/2012 00:00',
        '09/01/2012 00:00', '01/08/2014 00:00', '16/03/2015 00:00',
        '01/07/2015 00:00', '01/04/2017 00:00', '25/10/2021 00:00',
        '04/12/2017 00:00', '15/08/2019 00:00', '13/01/2020 00:00',
        '23/06/2022 00:00', '08/06/2022 00:00', '01/07/2001 00:00',
        '19/06/2006 00:00', '01/02/2008 00:00', '01/11/2010 00:00',
        '22/10/2012 00:00', '01/01/2014 00:00', '01/03/2001 00:00',
        '01/10/2014 00:00', '06/04/2017 00:00', '01/11/1995 00:00',
        '01/12/1995 00:00', '16/02/1998 00:00', '01/07/2002 00:00',
        '06/01/2003 00:00', '01/07/2003 00:00', '01/06/2007 00:00',
        '22/10/2007 00:00', '11/03/2013 00:00', '01/02/1993 00:00',
        '01/07/2008 00:00', '30/07/2007 00:00', '01/05/1992 00:00',
        '20/06/2018 00:00', '04/07/2022 00:00', '05/01/2005 00:00',
        '06/11/2006 00:00', '04/11/2013 00:00', '01/06/2015 00:00',
        '05/01/2017 00:00', '23/08/2016 00:00', '05/12/2018 00:00',
        '11/02/2026 00:00', '06/09/2022 00:00', '15/02/2023 00:00',
        '01/05/2016 00:00', '01/11/2012 00:00', '19/05/2014 00:00',
        '22/09/2008 00:00', '10/08/2021 00:00', '23/05/2022 00:00',
        '01/11/1985 00:00', '29/10/2001 00:00', '12/12/2002 00:00',
        '25/01/2010 00:00', '24/11/2017 00:00', '13/09/2022 00:00',
        '03/10/2000 00:00', '15/01/2002 00:00', '10/01/2005 00:00',
        '16/01/2012 00:00', '12/03/2012 00:00', '01/07/1985 00:00',
        '08/09/1986 00:00', '19/06/1989 00:00', '19/10/1992 00:00',
        '09/10/2002 00:00', '01/02/1992 00:00', '25/09/2017 00:00',
        '12/12/2016 00:00', '18/07/2022 00:00', '01/11/1990 00:00',
        '21/07/1997 00:00', '23/10/2023 00:00', '01/11/2023 00:00',
        '04/12/2023 00:00', '04/02/2019 00:00', '19/03/2024 00:00',
        '10/01/2025 00:00', '08/01/2025 00:00', '20/01/2025 00:00',
        '01/11/2020 00:00', '15/04/2025 00:00', '23/06/2025 00:00',
        '05/06/2025 00:00', '08/07/2025 00:00', '11/03/2019 00:00',
        '05/08/2025 00:00', '15/10/2025 00:00', '01/11/2025 00:00',
        '10/11/2025 00:00', '07/05/2024 00:00', '25/03/2026 00:00',
        '23/03/2026 00:00', '29/10/2018 00:00', '15/08/2016 00:00',
        '12/11/2001 00:00', '27/05/2024 00:00', '14/04/2022 00:00',
        '25/05/2020 00:00', '17/05/2021 00:00', '20/05/2024 00:00',
        '05/08/2024 00:00', '01/12/2003 00:00', '01/11/2007 00:00',
        '01/06/1979 00:00', '16/07/2018 00:00', '01/09/1988 00:00',
        '02/04/2001 00:00', '14/09/2015 00:00', '26/07/2021 00:00',
        '05/01/1998 00:00', '10/08/1998 00:00', '02/07/2001 00:00',
        '01/02/2003 00:00', '08/05/2001 00:00', '01/03/2000 00:00',
        '01/10/1995 00:00', '03/04/2000 00:00', '01/05/1997 00:00',
        '06/05/2022 00:00', '01/12/2024 00:00', '01/02/2025 00:00',
        '18/12/2023 00:00', '24/03/2025 00:00', '31/03/2025 00:00',
        '30/07/2024 00:00', '30/06/2025 00:00', '24/10/2024 00:00',
        '08/09/2025 00:00', '29/09/2025 00:00', '22/09/2025 00:00',
        '13/10/2025 00:00', '05/11/2025 00:00', '19/11/2025 00:00',
        '17/11/2025 00:00', '15/12/2025 00:00', '12/12/2025 00:00',
        '12/01/2026 00:00', '14/01/2026 00:00', '10/02/2026 00:00',
        '09/03/2026 00:00', '30/03/2026 00:00', '01/03/2026 00:00',
        '31/03/2026 00:00', '08/12/2008 00:00', '08/12/2014 00:00',
        '16/05/2022 00:00', '05/10/2023 00:00', '01/11/2004 00:00',
        '08/01/2008 00:00', '28/01/2019 00:00', '24/01/2020 00:00',
        '13/05/2024 00:00', '01/03/2019 00:00', '15/07/2024 00:00',
        '19/10/2023 00:00', '01/01/2010 00:00', '19/11/2013 00:00',
        '28/05/2025 00:00', '05/08/1996 00:00', '24/03/2026 00:00',
        '20/02/2023 00:00', '23/06/2023 00:00', '24/07/2023 00:00',
        '20/09/2021 00:00', '20/11/2023 00:00', '25/11/2019 00:00',
        '19/09/2016 00:00', '26/05/2003 00:00', '09/10/2014 00:00',
        '20/03/2018 00:00', '15/04/2022 00:00', '04/10/2004 00:00',
        '26/05/2017 00:00', '10/09/2015 00:00', '20/04/2020 00:00',
        '04/06/2012 00:00', '04/09/2017 00:00', '26/05/1997 00:00',
        '22/01/2018 00:00', '16/07/2025 00:00', '20/01/2026 00:00',
        '15/01/2026 00:00', '20/04/2023 00:00', '17/04/2026 00:00',
        '24/10/2016 00:00', '01/05/2018 00:00', '20/01/2020 00:00',
        '03/12/2001 00:00', '21/10/2013 00:00', '30/06/2014 00:00',
        '17/07/2017 00:00', '03/07/2012 00:00', '20/08/2012 00:00',
        '15/09/2008 00:00', '23/04/2018 00:00', '05/12/2016 00:00',
        '01/03/2016 00:00', '01/10/1998 00:00', '13/10/1997 00:00',
        '01/07/1986 00:00', '01/06/2012 00:00', '06/10/1992 00:00',
        '19/02/2007 00:00', '19/07/2013 00:00', '21/11/2018 00:00',
        '05/10/2021 00:00', '01/05/2003 00:00', '17/03/2021 00:00',
        '04/05/2023 00:00', '13/08/2018 00:00', '28/08/2023 00:00'],
       dtype=object),
 'reporting_date': array(['31/05/2023 00:00', '30/06/2023 00:00', '31/07/2023 00:00',
        '31/08/2023 00:00', '30/09/2023 00:00', '31/10/2023 00:00',
        '30/11/2023 00:00', '31/12/2023 00:00', '31/01/2024 00:00',
        '29/02/2024 00:00', '31/03/2024 00:00', '30/04/2024 00:00',
        '31/05/2024 00:00', '30/06/2024 00:00', '31/07/2024 00:00',

In [30]:
# Do contract categories always make sense for the broad category they are associated with?
df.groupby('contract_category')['broad_category'].unique()

contract_category
Acad-Rel Administrative              [Professional and Support]
Acad-Rel Computer                    [Professional and Support]
Acad-Rel ORS                               [Academic Education]
Academic Non-Clinical                                [Academic]
Academic Non-Clinical (Education)          [Academic Education]
Catering/Ancillary/Sport             [Professional and Support]
Cleaning                             [Professional and Support]
Clerical                             [Professional and Support]
Clerical Intern/Student              [Professional and Support]
Operational Intern/Student           [Professional and Support]
Research                                             [Research]
Research Academic                                    [Research]
Teaching Cons/Asst/Assoc                   [Academic Education]
Technical                            [Professional and Support]
Technical Intern/Student             [Professional and Support]
Name: broad_category, dtype: object

In [31]:
df.groupby('contract_type')['broad_contract_type'].unique()

contract_type
Fixed-term                         [Fixed]
Fixed-term - SPC                   [Fixed]
Fixed-term - acting up             [Fixed]
Perm - acting up               [Permanent]
Perm on temp appt              [Permanent]
Permanent                      [Permanent]
Permanent (Flex Retirement)    [Permanent]
Name: broad_contract_type, dtype: object

All contract types belong to only one broad contract type. All contract categories belong to only one broad category. This looks healthy

Are there any duplicate rows?

In [82]:
df.duplicated().sum()

np.int64(142)

In [83]:
# Drop 142 duplicate rows
df = df.drop_duplicates()

In [84]:
# Identify employees with more than one contract
df_multiple_contracts = df[df["Staff Key"].duplicated(keep=False)]
df_multiple_contracts

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date
0,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.2,01/07/1998 00:00,31/05/2023 00:00
1,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.8,01/07/1998 00:00,31/05/2023 00:00
2,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.4,01/08/2005 00:00,31/05/2023 00:00
3,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.6,01/08/2005 00:00,31/05/2023 00:00
4,1140481 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.2,01/07/2013 00:00,31/05/2023 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1110535 6,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 6,F,1.0,27/08/2018 00:00,30/09/2023 00:00
29996,1110539 6,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 6,M,1.0,21/11/2018 00:00,30/09/2023 00:00
29997,1110532 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,M,1.0,14/05/2018 00:00,30/09/2023 00:00
29998,1110534 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,01/08/2018 00:00,30/09/2023 00:00
29999,1110547 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/08/2019 00:00,30/09/2023 00:00

In [61]:
df_multiple_contracts[df_multiple_contracts["Staff Key"] == "1110547 7"]

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date
29813,1110547 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/08/2019 00:00,31/05/2023 00:00
29858,1110547 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/08/2019 00:00,30/06/2023 00:00
29904,1110547 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/08/2019 00:00,31/07/2023 00:00
29951,1110547 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/08/2019 00:00,31/08/2023 00:00
29999,1110547 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/08/2019 00:00,30/09/2023 00:00

In addition to 142 duplicate rows containing the same information in each column, there also seems to be instances where the same contract has been reported on different dates. As these are not distinct contracts the duplicates can be removed

In [85]:
cols = df.columns.drop("reporting_date")
df = df.drop_duplicates(subset=cols)

In [86]:
df

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date
0,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.2,01/07/1998 00:00,31/05/2023 00:00
1,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.8,01/07/1998 00:00,31/05/2023 00:00
2,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.4,01/08/2005 00:00,31/05/2023 00:00
3,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.6,01/08/2005 00:00,31/05/2023 00:00
4,1140481 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.2,01/07/2013 00:00,31/05/2023 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
29839,1100535 5,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Perm on temp appt,Clerical,Grade 5,F,1.0,13/08/2018 00:00,30/06/2023 00:00
29841,1110482 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Perm on temp appt,Acad-Rel Administrative,Grade 7,F,1.0,19/07/2013 00:00,30/06/2023 00:00
29859,1100568 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,05/10/2021 00:00,30/06/2023 00:00
29930,1130583 6,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term,Acad-Rel Administrative,Grade 6,F,1.0,28/08/2023 00:00,31/08/2023 00:00
29964,1150583 1,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term - SPC,Operational Intern/Student,Grade 1,M,1.0,15/08/2023 00:00,31/08/2023 00:00

There appears to be 1768 unique contracts. Much lower than the 30000 originally recorded.

In [87]:
# Redefine dataframe of employees with multiple contracts
df_multiple_contracts = df[df["Staff Key"].duplicated(keep=False)]
df_multiple_contracts

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date
0,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.2,01/07/1998 00:00,31/05/2023 00:00
1,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.8,01/07/1998 00:00,31/05/2023 00:00
2,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.4,01/08/2005 00:00,31/05/2023 00:00
3,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.6,01/08/2005 00:00,31/05/2023 00:00
4,1140481 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.2,01/07/2013 00:00,31/05/2023 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
29829,1000489 3,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Clerical,Grade 3,F,0.8,05/06/2017 00:00,31/05/2023 00:00
29831,1110533 7,Engineering and Physical Sciences,Faculty Office EPS,Academic Education,Permanent,Permanent,Acad-Rel ORS,Grade 7,M,1.0,16/07/2018 00:00,31/05/2023 00:00
29832,1002562 8,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Computer,Grade 8,M,1.0,01/09/1988 00:00,31/05/2023 00:00
29834,1020725 9,Engineering and Physical Sciences,Faculty Office EPS,Academic Education,Permanent,Permanent,Acad-Rel ORS,Grade 9,M,1.0,02/04/2001 00:00,31/05/2023 00:00
29964,1150583 1,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term - SPC,Operational Intern/Student,Grade 1,M,1.0,15/08/2023 00:00,31/08/2023 00:00

There appear to be 705 employees who have held more than one type of contract. How many employees have had contracts with more than one grade?

In [88]:
df_changing_grades = df_multiple_contracts[df_multiple_contracts.groupby("Staff Key")["grade"].transform("nunique") > 1]

In [89]:
df_changing_grades

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date
145,1150582 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Fixed,Fixed-term - SPC,Clerical Intern/Student,Grade 1,F,1.0,01/08/2023 00:00,31/08/2023 00:00
146,1150582 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Fixed,Fixed-term - SPC,Clerical Intern/Student,Grade 1,M,1.0,01/08/2023 00:00,31/08/2023 00:00
1535,1150583 1,"Arts, Humanities and Social Sciences","Inst for Global Peace, Security and Justice",Academic,Permanent,Permanent,Academic Non-Clinical,Professorial Range 1,F,1.0,01/01/2024 00:00,31/01/2024 00:00
7292,1160596 1,"Arts, Humanities and Social Sciences",Queen's Business School,Professional and Support,Fixed,Fixed-term - SPC,Clerical Intern/Student,Grade 1,M,1.0,23/07/2025 00:00,31/07/2025 00:00
21308,1160599 2,"Arts, Humanities and Social Sciences",School of Law,Academic,Permanent,Permanent,Academic Non-Clinical,Professorial Range 2,F,1.0,01/04/2026 00:00,30/04/2026 00:00
27039,1150583 1,Belfast Region City Deal,AMIC,Professional and Support,Fixed,Fixed-term - SPC,Operational Intern/Student,Grade 1,M,1.0,15/08/2023 00:00,31/08/2024 00:00
27827,1160599 2,Belfast Region City Deal,AMIC,Professional and Support,Fixed,Fixed-term,Technical,Grade 2,M,1.0,05/11/2025 00:00,30/11/2025 00:00
27828,1160599 2,Belfast Region City Deal,AMIC,Professional and Support,Fixed,Fixed-term,Technical,Grade 2,M,1.0,19/11/2025 00:00,30/11/2025 00:00
28632,1150582 1,Belfast Region City Deal,Momentum 1.0,Research,Fixed,Fixed-term,Research,ECIT Grade 1,M,1.0,24/07/2023 00:00,31/08/2024 00:00
29054,1160596 1,Belfast Region City Deal,Momentum 1.0,Research,Permanent,Permanent,Research,ECIT Grade 1,F,1.0,16/07/2025 00:00,31/07/2025 00:00
29165,1160598 1,Belfast Region City Deal,Momentum 1.0,Professional and Support,Fixed,Fixed-term - SPC,Clerical Intern/Student,Grade 1,M,1.0,01/10/2025 00:00,31/10/2025 00:00
29166,1160598 1,Belfast Region City Deal,Momentum 1.0,Professional and Support,Fixed,Fixed-term - SPC,Technical Intern/Student,Grade 1,M,1.0,06/10/2025 00:00,31/10/2025 00:00
29343,1160598 1,Belfast Region City Deal,Momentum 1.0,Research,Permanent,Permanent,Research,ECIT Grade 1,M,1.0,01/09/2025 00:00,31/01/2026 00:00
29964,1150583 1,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term - SPC,Operational Intern/Student,Grade 1,M,1.0,15/08/2023 00:00,31/08/2023 00:00

In [90]:
df_changing_grades["Staff Key"].unique()

array(['1150582 1', '1150583 1', '1160596 1', '1160599 2', '1160598 1'],
      dtype=object)

Only 5 out of 1336 staff appear to have changed grades. There is an issue with the Staff Key whereby the grade is used at the end of the Staff ID number. This means Staff Key is not a unique identifier for a staff member, but rather for a contract. 

Let's go back and identify unique staff members

In [92]:
df_multiple_contracts["Staff ID"] = df_multiple_contracts["Staff Key"].str[:7]

C:\Users\Niall.Russell\AppData\Local\Temp\ipykernel_31684\2770146454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_multiple_contracts["Staff ID"] = df_multiple_contracts["Staff Key"].str[:7]

In [93]:
df_multiple_contracts

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date,Staff ID
0,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.2,01/07/1998 00:00,31/05/2023 00:00,1140547
1,1140547C4,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,AC4,F,0.8,01/07/1998 00:00,31/05/2023 00:00,1140547
2,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.4,01/08/2005 00:00,31/05/2023 00:00,1140403
3,1140403 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.6,01/08/2005 00:00,31/05/2023 00:00,1140403
4,1140481 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Academic,Permanent,Perm on temp appt,Academic Non-Clinical,Professorial Range 1,M,0.2,01/07/2013 00:00,31/05/2023 00:00,1140481
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29829,1000489 3,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Clerical,Grade 3,F,0.8,05/06/2017 00:00,31/05/2023 00:00,1000489
29831,1110533 7,Engineering and Physical Sciences,Faculty Office EPS,Academic Education,Permanent,Permanent,Acad-Rel ORS,Grade 7,M,1.0,16/07/2018 00:00,31/05/2023 00:00,1110533
29832,1002562 8,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Permanent,Permanent,Acad-Rel Computer,Grade 8,M,1.0,01/09/1988 00:00,31/05/2023 00:00,1002562
29834,1020725 9,Engineering and Physical Sciences,Faculty Office EPS,Academic Education,Permanent,Permanent,Acad-Rel ORS,Grade 9,M,1.0,02/04/2001 00:00,31/05/2023 00:00,1020725
29964,1150583 1,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term - SPC,Operational Intern/Student,Grade 1,M,1.0,15/08/2023 00:00,31/08/2023 00:00,1150583

In [94]:
df_changing_grades = df_multiple_contracts[df_multiple_contracts.groupby("Staff ID")["grade"].transform("nunique") > 1]

In [95]:
df_changing_grades

,Staff Key,faculty,school,broad_category,broad_contract_type,contract_type,contract_category,grade,gender,calc_fte,start_date,reporting_date,Staff ID
37,1120571 7,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,1.0,07/02/2022 00:00,31/05/2023 00:00,1120571
145,1150582 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Fixed,Fixed-term - SPC,Clerical Intern/Student,Grade 1,F,1.0,01/08/2023 00:00,31/08/2023 00:00,1150582
146,1150582 1,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Fixed,Fixed-term - SPC,Clerical Intern/Student,Grade 1,M,1.0,01/08/2023 00:00,31/08/2023 00:00,1150582
239,1150584 2,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Fixed,Fixed-term - SPC,Clerical,Grade 2,F,1.0,16/10/2023 00:00,31/10/2023 00:00,1150584
655,1120571 7,"Arts, Humanities and Social Sciences",Faculty Office AHSS,Professional and Support,Permanent,Permanent,Acad-Rel Administrative,Grade 7,F,0.6,07/02/2022 00:00,30/06/2024 00:00,1120571
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29470,1160600 1,Belfast Region City Deal,Momentum 1.0,Research,Permanent,Permanent,Research,ECIT Grade 1,M,1.0,01/04/2026 00:00,30/04/2026 00:00,1160600
29820,1120556 7,Engineering and Physical Sciences,Faculty Office EPS,Academic Education,Fixed,Fixed-term,Acad-Rel ORS,Grade 7,M,1.0,25/05/2020 00:00,31/05/2023 00:00,1120556
29822,1130565 7,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term,Acad-Rel Computer,Grade 7,M,1.0,17/05/2021 00:00,31/05/2023 00:00,1130565
29824,1120556 8,Engineering and Physical Sciences,Faculty Office EPS,Academic Education,Fixed,Fixed-term,Acad-Rel ORS,Grade 8,M,1.0,01/04/2020 00:00,31/05/2023 00:00,1120556
29964,1150583 1,Engineering and Physical Sciences,Faculty Office EPS,Professional and Support,Fixed,Fixed-term - SPC,Operational Intern/Student,Grade 1,M,1.0,15/08/2023 00:00,31/08/2023 00:00,1150583